package kurou.kodriver.domain.model

enum class DebugStateCardKey {
    SIMULATOR,
    FLAG_INFO,
    GAME_PHASE,
    SESSION,
    YELLOW_FLAG_STATE,
    CURRENT_LAP,
    SIDE_BY_SIDE_VEHICLES,
    BEST_LAP,
    TYRE_TEMPERATURE,
    TYRE_CARCASS_TEMPERATURE,
    TYRE_WEAR,
    FUEL_CONSUMPTION,
    PIT_TIMING_REMAINING_LAPS,
}
