package kurou.kodriver.domain.model

const val GT7_PS5_REMAINING_FUEL_LAPS_DEFAULT = 3
const val GT7_PS5_REMAINING_FUEL_LAPS_MIN = 1
const val GT7_PS5_REMAINING_FUEL_LAPS_MAX = 5

const val GT7_PS5_REMAINING_FUEL_LAPS_READOUT_TEXT_DEFAULT = "燃料は残り約{laps}周"
const val GT7_PS5_REMAINING_FUEL_LAPS_EMPTY_READOUT_TEXT_DEFAULT = "燃料残り1周未満"
const val GT7_PS5_REMAINING_FUEL_LAPS_PLACEHOLDER = "{laps}"
