package kurou.kodriver.domain.model

const val LMU_WINDOWS_PIT_TIMING_VIRTUAL_ENERGY_LAPS_DEFAULT = 3
const val LMU_WINDOWS_PIT_TIMING_TYRE_WEAR_LAPS_DEFAULT = 3
const val LMU_WINDOWS_PIT_TIMING_LAPS_MIN = 1
const val LMU_WINDOWS_PIT_TIMING_LAPS_MAX = 5

const val LMU_WINDOWS_PIT_TIMING_VIRTUAL_ENERGY_READOUT_TEXT_DEFAULT = "エナジー切れのため{laps}周以内にピットイン"
const val LMU_WINDOWS_PIT_TIMING_VIRTUAL_ENERGY_IMMINENT_READOUT_TEXT_DEFAULT = "エナジー切れのため必ずピットイン"
const val LMU_WINDOWS_PIT_TIMING_LAPS_PLACEHOLDER = "{laps}"

const val LMU_WINDOWS_PIT_TIMING_TYRE_WEAR_READOUT_TEXT_DEFAULT = "タイヤ摩耗のため{laps}周以内にピットイン"
const val LMU_WINDOWS_PIT_TIMING_TYRE_WEAR_IMMINENT_READOUT_TEXT_DEFAULT = "タイヤ摩耗のため必ずピットイン"
