name: Build Android

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/_build-android-release.yml
    with:
      ref: ${{ github.ref }}
    secrets: inherit
