name: Build Windows

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: ./.github/actions/setup

      - name: Get version
        id: version
        shell: bash
        run: echo "version=$(grep '^appVersion=' gradle.properties | cut -d'=' -f2)" >> $GITHUB_OUTPUT

      - name: Build MSI
        run: ./gradlew :app:desktopApp:packageMsi

      - name: Rename MSI
        shell: bash
        run: mv app/desktopApp/build/compose/binaries/main/msi/*.msi app/desktopApp/build/compose/binaries/main/msi/KoDriver-windows-${{ steps.version.outputs.version }}-release.msi

      - name: Upload MSI
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: KoDriver-windows-${{ steps.version.outputs.version }}-release
          path: app/desktopApp/build/compose/binaries/main/msi/KoDriver-windows-${{ steps.version.outputs.version }}-release.msi
          retention-days: 30
