name: Build Apps

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-android:
    name: Build Android
    uses: ./.github/workflows/_build-android-release.yml
    with:
      ref: ${{ github.ref }}
    secrets: inherit

  build-windows:
    name: Build Windows
    uses: ./.github/workflows/_build-windows-msi.yml
    with:
      ref: ${{ github.ref }}
